### ISSUE TITLE
font request: Geologica

### ISSUE THREAD

**Issue by bstro** [fontsource/font-files#24]
### Describe the feature you'd like to request

I'd love to see Geologica support.
https://fonts.google.com/specimen/Geologica.

Otherwise, thanks for your work on this; I'm finding it super helpful for my project.

**Comment by jwr1** [comment]
Please use the [issue template](https://github.com/fontsource/font-files/issues/new?assignees=&labels=font+request&projects=&template=font.yml&title=Font+Request%3A+) in the font-files repo for future font requests.

**Comment by bstro** [comment]
Will do, thanks for letting me know.
