### ISSUE TITLE
Font Request: Instrument Sans

### ISSUE THREAD

**Issue by Mrahmani71** [fontsource/font-files#31]
### Font Name

Instrument Sans

### Link to font source

https://fonts.google.com/specimen/Instrument+Sans
https://github.com/Instrument/instrument-sans

### Link to font license
https://github.com/Instrument/instrument-sans#license
https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL

**Comment by ayuhito** [comment]
It is now available at: https://fontsource.org/fonts/instrument-sans
