### ISSUE TITLE
Font Request: Geist

### ISSUE THREAD

**Issue by pn320** [fontsource/font-files#46]
### Font Name

Geist (just released by Vercel) available here (https://vercel.com/font)

### Link to font source

https://github.com/vercel/geist-font

### Link to font license

https://github.com/vercel/geist-font/blob/main/LICENSE.TXT

**Comment by jwr1** [comment]
There is already an open issue in Google Fonts, so it's likely to be added to fontsource: https://github.com/google/fonts/issues/6922.

**Comment by pn320** [comment]
Perfect thank you so much!

**Comment by pn320** [comment]
Perfect thank you so much!

**Comment by jwr1** [comment]
We'll keep this open to track it.
