### ISSUE TITLE
Inter 4

### ISSUE THREAD

**Issue by MonsterDeveloper** [fontsource/font-files#55]
### Description

Recently a [new major version 4.0 of Inter](https://github.com/rsms/inter/releases/tag/v4.0) typeface was released.

I believe fontsource should update the `font-files` accordingly to use the latest version.

**Comment by shyakadavis** [comment]
Hello, @ayuhito,

> We programmatically mirror Google Fonts 1:1.

Does this mean that with the resolution of https://github.com/google/fonts/issues/3429, future installations will automatically be of Inter 4?

**Comment by shyakadavis** [comment]
From Marc, they decided to stick to the original name.

> The answer is in, we're not going to rename the family.

https://github.com/rsms/inter/pull/678#issuecomment-2111995607

> If they update the original "Inter" family instead, our existing package will reflect that too.

Thanks. I guess all we have to do is wait for them publish, right?

**Comment by ayuhito** [comment]
If that's the case, then yes we just have to wait for a release. 

Note that the update will look like a normal patch release on Fontsource, but at least for users who don't like the changes, they can pin their package versions 👍

**Comment by kairader-remo** [comment]
Outside of manually checking Google Fonts, is there a way to know when the new version is published?

**Comment by shyakadavis** [comment]
@kairader-remo 

The closest to a date I could was Marc's comment:

> Family should land on the Google Fonts website in approximately two weeks.

https://github.com/google/fonts/issues/3429#issuecomment-2154822343

**Comment by shyakadavis** [comment]
Hello 👋 (Sorry for the noise)

Am I correct in assuming that the new release `5.0.18` -> `5.0.19` effectively upgrades the version? (Couldn't find a place to manually check the Google version)

Noticed in the packages there was `@fontsource/inter@5.0.18`.

**Comment by ayuhito** [comment]
It has not been updated to Inter 4 yet. This is an unrelated update.

You can see [here](https://github.com/orgs/google/projects/74/views/4?filterQuery=-status%3A%22PR+GF%22++inter) that it is currently in sandbox. Once it is moved to production, we should then be able to mirror that.

**Comment by shyakadavis** [comment]
https://github.com/google/fonts/issues/3429#issuecomment-2260428585 🎉

**Comment by ayuhito** [comment]
Released in https://github.com/fontsource/font-files/commit/d76f3ebca2dd4bb3c4ac9f362ce999fe45785de6.
