### ISSUE TITLE
Font Request: LXGW WenKai（霞鹜文楷）

### ISSUE THREAD

**Issue by 7890qwaszx** [fontsource/font-files#57]
### Font Name

LXGW WenKai（霞鹜文楷）

### Link to font source

https://github.com/lxgw/LxgwWenKai

### Link to font license

[SIL Open Font License 1.1](https://github.com/lxgw/LxgwWenKai/blob/main/OFL.txt)

**Comment by ayuhito** [comment]
I believe we already have this: https://github.com/lxgw/LxgwWenKai
