### ISSUE TITLE
Font Request: Pretendard

### ISSUE THREAD

**Issue by dungsil** [fontsource/font-files#62]
### Font Name

Pretendard

### Link to font source

https://github.com/orioncactus/pretendard

### Link to font license

https://github.com/orioncactus/pretendard?tab=OFL-1.1-1-ov-file#readme

### Additional context

Contains 3 subsets:
 - Pretendard
 - Pretendard JP
 - Pretendard GOV

Includes variable fonts
 - Pretendard
 - Pretendard Variable

**Comment by ayuhito** [comment]
Closed in #84.
