### ISSUE TITLE
Font Request: Add UnifontEX

### ISSUE THREAD

**Issue by stgiga** [fontsource/font-files#73]
### Font Name

UnifontEX

### Link to font source

http://stgiga.github.io/UnifontEX

### Link to font license

https://opensource.org/license/ofl-1-1

### Additional context

Regular Unifont is in Fontsource because it is SIL OFLv1.1, and UnifontEX (my extended fork of GNU Unifont) is based on Unifont versions that have that. 
UnifontEX basically merges Unicode's Plane 0 with Plane 1 as best as possible (something not done by upstream Unifont. Also this gives emoji support plus more historic scripts.)
 It also has been given extra optimizations for higher compatibility, and I've pre-made WOFF and WOFF2 versions (as well as all the other webfont formats, such as EOT and iOS Safari SVG, and of course the TrueType.)
It also has special OpenType tables that aren't in regular Unifont.

Since Unifont is already in Fontsource, there is precedent for adding UnifontEX.

**Comment by stgiga** [comment]
I should mention that I'm soon going to do an internal metadata update that changes no functionality and simply fixes an accidental omission of one of two people Roman Czyborra credited as a source of encouragement in the early days of Unifont, and the omission happened due to me only knowing said person with his professor title plus surname, and I didn't know anything else until I had already made my February 2nd, 2024 update. I have to regenerate the font in quite a few formats to add the info, and correct certain parts of the FONTLOG and Comments section of FontForge's PfEd table to reflect newer background information which is in my README.md file. This won't change any functionality.

**Comment by ayuhito** [comment]
Closed in #83.

**Comment by stgiga** [comment]
> Closed in #83.

In the time since this happened, I updated UnifontEX to support Unicode 15.1, and I'm *hoping* I was able to add the updated version properly. I gave it a version of 1.1 in the metadata, just so you know.
